changelog:
  exclude:
    labels:
      - "Type: Release"

  categories:
    - title: Security Fixes
      labels: ["Type: Security"]
    - title: Breaking Changes
      labels: ["Type: Breaking Change"]
    - title: Features
      labels: ["Type: Feature"]
    - title: Bug Fixes
      labels: ["Type: Bug"]
    - title: Documentation
      labels: ["Type: Documentation"]
    - title: Refactoring
      labels: ["Type: Refactoring"]
    - title: Testing
      labels: ["Type: Testing"]
    - title: CI
      labels: ["Type: CI"]
    - title: Dependency Updates
      labels: ["Type: Dependencies", "dependencies"]
    - title: Other Changes
      labels: ["*"]
